version: '3.8'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mariadb-server1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: m1_s3cr3t
      MYSQL_DATABASE: gestion_gym
    networks:
      - mariadb_network

networks:
  mariadb_network:
    driver: bridge


